export const PROJECT_CONFIG: any = {
  project1: {
    variant: "dark",
    title1: "Project 1",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 1",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 1",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
  project2: {
    variant: "dark",
    title1: "Project 2",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 2",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 2",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
  project3: {
    variant: "dark",
    title1: "Project 3",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 3",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 3",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
  project4: {
    variant: "dark",
    title1: "Project 4",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 4",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 4",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
  project5: {
    variant: "dark",
    title1: "Project 5",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 5",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 5",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
  project6: {
    variant: "dark",
    title1: "Project 6",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 6",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 6",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
  project7: {
    variant: "dark",
    title1: "Project 7",
    caption1: "Caption 1",
    img1: "https://i.ibb.co/hZp03Rs/desktop-large2.jpg",
    position1: "middle",
    color1: "dark",
    title2: "Project 7",
    caption2: "Caption 2",
    img2: "https://i.ibb.co/VSzk3PM/paint-web.jpg",
    position2: "bottom",
    color2: "light",
    title3: "Project 7",
    caption3: "Caption 3",
    img3: "https://i.ibb.co/vHKWrn7/one-click-away.jpg",
    position3: "top",
    color3: "dark",
  },
};
